### ISSUE TITLE
Linux 6.9+

### ISSUE THREAD

**Issue by danielnorberg** [oracle/linux-uek#25] opened 2024-06-21 08:13 UTC
Are there any plans to update [ueknext/latest](https://github.com/oracle/linux-uek/tree/ueknext/latest) to 6.9 or later?

**Comment by YoderExMachina** [comment] 2024-06-21 12:45
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Closed by YoderExMachina** 2024-06-21 12:45 UTC

**Comment by darrenkenny** [comment] 2024-06-21 13:21
@danielnorberg - to answer your question, we are working on it, so stay tuned.

**Comment by darrenkenny** [comment] 2024-06-26 07:51
To explain what is causing the delay, even though the UIEK-next release is technically unsupported, we still perform qualification prior to releasing it.

During this qualification, a possible filesystem corruption issue was discovered - we are investigating the cause of this, and as a result it is further delaying the release of the v6.9 release.

We expect to be able to deliver a update within the next week or so.

**Comment by darrenkenny** [comment] 2024-07-01 16:54
@danielnorberg - FYI, we've uploaded the source and RPMs for v6.9 now

**Comment by danielnorberg** [comment] 2024-07-01 17:08
@darrenkenny Good to hear, thank you!
